// Generated by gencpp from file pcl_segmentation/Centroid.msg
// DO NOT EDIT!


#ifndef PCL_SEGMENTATION_MESSAGE_CENTROID_H
#define PCL_SEGMENTATION_MESSAGE_CENTROID_H

#include <ros/service_traits.h>


#include <pcl_segmentation/CentroidRequest.h>
#include <pcl_segmentation/CentroidResponse.h>


namespace pcl_segmentation
{

struct Centroid
{

typedef CentroidRequest Request;
typedef CentroidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Centroid
} // namespace pcl_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_segmentation::Centroid > {
  static const char* value()
  {
    return "9524e425aabfd4146fc2853e661c3909";
  }

  static const char* value(const ::pcl_segmentation::Centroid&) { return value(); }
};

template<>
struct DataType< ::pcl_segmentation::Centroid > {
  static const char* value()
  {
    return "pcl_segmentation/Centroid";
  }

  static const char* value(const ::pcl_segmentation::Centroid&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_segmentation::CentroidRequest> should match
// service_traits::MD5Sum< ::pcl_segmentation::Centroid >
template<>
struct MD5Sum< ::pcl_segmentation::CentroidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_segmentation::Centroid >::value();
  }
  static const char* value(const ::pcl_segmentation::CentroidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_segmentation::CentroidRequest> should match
// service_traits::DataType< ::pcl_segmentation::Centroid >
template<>
struct DataType< ::pcl_segmentation::CentroidRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_segmentation::Centroid >::value();
  }
  static const char* value(const ::pcl_segmentation::CentroidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_segmentation::CentroidResponse> should match
// service_traits::MD5Sum< ::pcl_segmentation::Centroid >
template<>
struct MD5Sum< ::pcl_segmentation::CentroidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_segmentation::Centroid >::value();
  }
  static const char* value(const ::pcl_segmentation::CentroidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_segmentation::CentroidResponse> should match
// service_traits::DataType< ::pcl_segmentation::Centroid >
template<>
struct DataType< ::pcl_segmentation::CentroidResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_segmentation::Centroid >::value();
  }
  static const char* value(const ::pcl_segmentation::CentroidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SEGMENTATION_MESSAGE_CENTROID_H
