// Generated by gencpp from file pcl_segmentation/MaskFromCuboid.msg
// DO NOT EDIT!


#ifndef PCL_SEGMENTATION_MESSAGE_MASKFROMCUBOID_H
#define PCL_SEGMENTATION_MESSAGE_MASKFROMCUBOID_H

#include <ros/service_traits.h>


#include <pcl_segmentation/MaskFromCuboidRequest.h>
#include <pcl_segmentation/MaskFromCuboidResponse.h>


namespace pcl_segmentation
{

struct MaskFromCuboid
{

typedef MaskFromCuboidRequest Request;
typedef MaskFromCuboidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MaskFromCuboid
} // namespace pcl_segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_segmentation::MaskFromCuboid > {
  static const char* value()
  {
    return "7f2ad986538b8155db3f7c7f012bfbc9";
  }

  static const char* value(const ::pcl_segmentation::MaskFromCuboid&) { return value(); }
};

template<>
struct DataType< ::pcl_segmentation::MaskFromCuboid > {
  static const char* value()
  {
    return "pcl_segmentation/MaskFromCuboid";
  }

  static const char* value(const ::pcl_segmentation::MaskFromCuboid&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_segmentation::MaskFromCuboidRequest> should match
// service_traits::MD5Sum< ::pcl_segmentation::MaskFromCuboid >
template<>
struct MD5Sum< ::pcl_segmentation::MaskFromCuboidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_segmentation::MaskFromCuboid >::value();
  }
  static const char* value(const ::pcl_segmentation::MaskFromCuboidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_segmentation::MaskFromCuboidRequest> should match
// service_traits::DataType< ::pcl_segmentation::MaskFromCuboid >
template<>
struct DataType< ::pcl_segmentation::MaskFromCuboidRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_segmentation::MaskFromCuboid >::value();
  }
  static const char* value(const ::pcl_segmentation::MaskFromCuboidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_segmentation::MaskFromCuboidResponse> should match
// service_traits::MD5Sum< ::pcl_segmentation::MaskFromCuboid >
template<>
struct MD5Sum< ::pcl_segmentation::MaskFromCuboidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_segmentation::MaskFromCuboid >::value();
  }
  static const char* value(const ::pcl_segmentation::MaskFromCuboidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_segmentation::MaskFromCuboidResponse> should match
// service_traits::DataType< ::pcl_segmentation::MaskFromCuboid >
template<>
struct DataType< ::pcl_segmentation::MaskFromCuboidResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_segmentation::MaskFromCuboid >::value();
  }
  static const char* value(const ::pcl_segmentation::MaskFromCuboidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_SEGMENTATION_MESSAGE_MASKFROMCUBOID_H
