(cl:defpackage face_detection-srv
  (:use )
  (:export
   "FACEDETECTION"
   "<FACEDETECTION-REQUEST>"
   "FACEDETECTION-REQUEST"
   "<FACEDETECTION-RESPONSE>"
   "FACEDETECTION-RESPONSE"
   "FACEDETECTIONPCL"
   "<FACEDETECTIONPCL-REQUEST>"
   "FACEDETECTIONPCL-REQUEST"
   "<FACEDETECTIONPCL-RESPONSE>"
   "FACEDETECTIONPCL-RESPONSE"
  ))

