// Generated by gencpp from file tf_module/ApplyTransformRequest.msg
// DO NOT EDIT!


#ifndef TF_MODULE_MESSAGE_APPLYTRANSFORMREQUEST_H
#define TF_MODULE_MESSAGE_APPLYTRANSFORMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/TransformStamped.h>

namespace tf_module
{
template <class ContainerAllocator>
struct ApplyTransformRequest_
{
  typedef ApplyTransformRequest_<ContainerAllocator> Type;

  ApplyTransformRequest_()
    : points()
    , transform()  {
    }
  ApplyTransformRequest_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , transform(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _transform_type;
  _transform_type transform;





  typedef boost::shared_ptr< ::tf_module::ApplyTransformRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_module::ApplyTransformRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ApplyTransformRequest_

typedef ::tf_module::ApplyTransformRequest_<std::allocator<void> > ApplyTransformRequest;

typedef boost::shared_ptr< ::tf_module::ApplyTransformRequest > ApplyTransformRequestPtr;
typedef boost::shared_ptr< ::tf_module::ApplyTransformRequest const> ApplyTransformRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_module::ApplyTransformRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tf_module::ApplyTransformRequest_<ContainerAllocator1> & lhs, const ::tf_module::ApplyTransformRequest_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.transform == rhs.transform;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tf_module::ApplyTransformRequest_<ContainerAllocator1> & lhs, const ::tf_module::ApplyTransformRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tf_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_module::ApplyTransformRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::ApplyTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::ApplyTransformRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aec84275f0d28f8c86ef5c1b9bdb144";
  }

  static const char* value(const ::tf_module::ApplyTransformRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aec84275f0d28f8ULL;
  static const uint64_t static_value2 = 0xc86ef5c1b9bdb144ULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_module/ApplyTransformRequest";
  }

  static const char* value(const ::tf_module::ApplyTransformRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points # point we want to transform\n"
"geometry_msgs/TransformStamped transform #the transform we want to use\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::tf_module::ApplyTransformRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.transform);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApplyTransformRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_module::ApplyTransformRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_module::ApplyTransformRequest_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "transform: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.transform);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_MODULE_MESSAGE_APPLYTRANSFORMREQUEST_H
