// Generated by gencpp from file tf_module/BaseTransform.msg
// DO NOT EDIT!


#ifndef TF_MODULE_MESSAGE_BASETRANSFORM_H
#define TF_MODULE_MESSAGE_BASETRANSFORM_H

#include <ros/service_traits.h>


#include <tf_module/BaseTransformRequest.h>
#include <tf_module/BaseTransformResponse.h>


namespace tf_module
{

struct BaseTransform
{

typedef BaseTransformRequest Request;
typedef BaseTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BaseTransform
} // namespace tf_module


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_module::BaseTransform > {
  static const char* value()
  {
    return "e34396cb6a4d6ca05fcd61fe22fd3a11";
  }

  static const char* value(const ::tf_module::BaseTransform&) { return value(); }
};

template<>
struct DataType< ::tf_module::BaseTransform > {
  static const char* value()
  {
    return "tf_module/BaseTransform";
  }

  static const char* value(const ::tf_module::BaseTransform&) { return value(); }
};


// service_traits::MD5Sum< ::tf_module::BaseTransformRequest> should match
// service_traits::MD5Sum< ::tf_module::BaseTransform >
template<>
struct MD5Sum< ::tf_module::BaseTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_module::BaseTransform >::value();
  }
  static const char* value(const ::tf_module::BaseTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_module::BaseTransformRequest> should match
// service_traits::DataType< ::tf_module::BaseTransform >
template<>
struct DataType< ::tf_module::BaseTransformRequest>
{
  static const char* value()
  {
    return DataType< ::tf_module::BaseTransform >::value();
  }
  static const char* value(const ::tf_module::BaseTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_module::BaseTransformResponse> should match
// service_traits::MD5Sum< ::tf_module::BaseTransform >
template<>
struct MD5Sum< ::tf_module::BaseTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_module::BaseTransform >::value();
  }
  static const char* value(const ::tf_module::BaseTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_module::BaseTransformResponse> should match
// service_traits::DataType< ::tf_module::BaseTransform >
template<>
struct DataType< ::tf_module::BaseTransformResponse>
{
  static const char* value()
  {
    return DataType< ::tf_module::BaseTransform >::value();
  }
  static const char* value(const ::tf_module::BaseTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_MODULE_MESSAGE_BASETRANSFORM_H
