// Generated by gencpp from file tf_module/BaseTransformResponse.msg
// DO NOT EDIT!


#ifndef TF_MODULE_MESSAGE_BASETRANSFORMRESPONSE_H
#define TF_MODULE_MESSAGE_BASETRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace tf_module
{
template <class ContainerAllocator>
struct BaseTransformResponse_
{
  typedef BaseTransformResponse_<ContainerAllocator> Type;

  BaseTransformResponse_()
    : new_points()  {
    }
  BaseTransformResponse_(const ContainerAllocator& _alloc)
    : new_points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PointStamped_<ContainerAllocator> >> _new_points_type;
  _new_points_type new_points;





  typedef boost::shared_ptr< ::tf_module::BaseTransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_module::BaseTransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BaseTransformResponse_

typedef ::tf_module::BaseTransformResponse_<std::allocator<void> > BaseTransformResponse;

typedef boost::shared_ptr< ::tf_module::BaseTransformResponse > BaseTransformResponsePtr;
typedef boost::shared_ptr< ::tf_module::BaseTransformResponse const> BaseTransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_module::BaseTransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_module::BaseTransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tf_module::BaseTransformResponse_<ContainerAllocator1> & lhs, const ::tf_module::BaseTransformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.new_points == rhs.new_points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tf_module::BaseTransformResponse_<ContainerAllocator1> & lhs, const ::tf_module::BaseTransformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tf_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_module::BaseTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::BaseTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::BaseTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f506729f2e47b07dba1cf7734b6fba21";
  }

  static const char* value(const ::tf_module::BaseTransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf506729f2e47b07dULL;
  static const uint64_t static_value2 = 0xba1cf7734b6fba21ULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_module/BaseTransformResponse";
  }

  static const char* value(const ::tf_module::BaseTransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped[]  new_points      # the transformed point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tf_module::BaseTransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BaseTransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_module::BaseTransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_module::BaseTransformResponse_<ContainerAllocator>& v)
  {
    s << indent << "new_points[]" << std::endl;
    for (size_t i = 0; i < v.new_points.size(); ++i)
    {
      s << indent << "  new_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.new_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_MODULE_MESSAGE_BASETRANSFORMRESPONSE_H
