// Generated by gencpp from file tf_module/LatestTransform.msg
// DO NOT EDIT!


#ifndef TF_MODULE_MESSAGE_LATESTTRANSFORM_H
#define TF_MODULE_MESSAGE_LATESTTRANSFORM_H

#include <ros/service_traits.h>


#include <tf_module/LatestTransformRequest.h>
#include <tf_module/LatestTransformResponse.h>


namespace tf_module
{

struct LatestTransform
{

typedef LatestTransformRequest Request;
typedef LatestTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LatestTransform
} // namespace tf_module


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf_module::LatestTransform > {
  static const char* value()
  {
    return "fe383c2fd1e0d2ae722c2c2191871719";
  }

  static const char* value(const ::tf_module::LatestTransform&) { return value(); }
};

template<>
struct DataType< ::tf_module::LatestTransform > {
  static const char* value()
  {
    return "tf_module/LatestTransform";
  }

  static const char* value(const ::tf_module::LatestTransform&) { return value(); }
};


// service_traits::MD5Sum< ::tf_module::LatestTransformRequest> should match
// service_traits::MD5Sum< ::tf_module::LatestTransform >
template<>
struct MD5Sum< ::tf_module::LatestTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf_module::LatestTransform >::value();
  }
  static const char* value(const ::tf_module::LatestTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_module::LatestTransformRequest> should match
// service_traits::DataType< ::tf_module::LatestTransform >
template<>
struct DataType< ::tf_module::LatestTransformRequest>
{
  static const char* value()
  {
    return DataType< ::tf_module::LatestTransform >::value();
  }
  static const char* value(const ::tf_module::LatestTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf_module::LatestTransformResponse> should match
// service_traits::MD5Sum< ::tf_module::LatestTransform >
template<>
struct MD5Sum< ::tf_module::LatestTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf_module::LatestTransform >::value();
  }
  static const char* value(const ::tf_module::LatestTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf_module::LatestTransformResponse> should match
// service_traits::DataType< ::tf_module::LatestTransform >
template<>
struct DataType< ::tf_module::LatestTransformResponse>
{
  static const char* value()
  {
    return DataType< ::tf_module::LatestTransform >::value();
  }
  static const char* value(const ::tf_module::LatestTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_MODULE_MESSAGE_LATESTTRANSFORM_H
