// Generated by gencpp from file tf_module/TfTransformResponse.msg
// DO NOT EDIT!


#ifndef TF_MODULE_MESSAGE_TFTRANSFORMRESPONSE_H
#define TF_MODULE_MESSAGE_TFTRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>
#include <sensor_msgs/PointCloud2.h>
#include <geometry_msgs/PointStamped.h>
#include <geometry_msgs/Pose.h>

namespace tf_module
{
template <class ContainerAllocator>
struct TfTransformResponse_
{
  typedef TfTransformResponse_<ContainerAllocator> Type;

  TfTransformResponse_()
    : target_pose_array()
    , target_pointcloud()
    , target_point()
    , translation_and_rotation()  {
    }
  TfTransformResponse_(const ContainerAllocator& _alloc)
    : target_pose_array(_alloc)
    , target_pointcloud(_alloc)
    , target_point(_alloc)
    , translation_and_rotation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _target_pose_array_type;
  _target_pose_array_type target_pose_array;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _target_pointcloud_type;
  _target_pointcloud_type target_pointcloud;

   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _target_point_type;
  _target_point_type target_point;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _translation_and_rotation_type;
  _translation_and_rotation_type translation_and_rotation;





  typedef boost::shared_ptr< ::tf_module::TfTransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tf_module::TfTransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TfTransformResponse_

typedef ::tf_module::TfTransformResponse_<std::allocator<void> > TfTransformResponse;

typedef boost::shared_ptr< ::tf_module::TfTransformResponse > TfTransformResponsePtr;
typedef boost::shared_ptr< ::tf_module::TfTransformResponse const> TfTransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tf_module::TfTransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tf_module::TfTransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tf_module::TfTransformResponse_<ContainerAllocator1> & lhs, const ::tf_module::TfTransformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose_array == rhs.target_pose_array &&
    lhs.target_pointcloud == rhs.target_pointcloud &&
    lhs.target_point == rhs.target_point &&
    lhs.translation_and_rotation == rhs.translation_and_rotation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tf_module::TfTransformResponse_<ContainerAllocator1> & lhs, const ::tf_module::TfTransformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tf_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tf_module::TfTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tf_module::TfTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::TfTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tf_module::TfTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::TfTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tf_module::TfTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tf_module::TfTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9178a83ee8c30ff7fea890b8e766ae7";
  }

  static const char* value(const ::tf_module::TfTransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9178a83ee8c30ffULL;
  static const uint64_t static_value2 = 0x7fea890b8e766ae7ULL;
};

template<class ContainerAllocator>
struct DataType< ::tf_module::TfTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tf_module/TfTransformResponse";
  }

  static const char* value(const ::tf_module::TfTransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tf_module::TfTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray target_pose_array\n"
"sensor_msgs/PointCloud2 target_pointcloud\n"
"geometry_msgs/PointStamped target_point\n"
"geometry_msgs/Pose translation_and_rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
;
  }

  static const char* value(const ::tf_module::TfTransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tf_module::TfTransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose_array);
      stream.next(m.target_pointcloud);
      stream.next(m.target_point);
      stream.next(m.translation_and_rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TfTransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tf_module::TfTransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tf_module::TfTransformResponse_<ContainerAllocator>& v)
  {
    s << indent << "target_pose_array: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose_array);
    s << indent << "target_pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pointcloud);
    s << indent << "target_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_point);
    s << indent << "translation_and_rotation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.translation_and_rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TF_MODULE_MESSAGE_TFTRANSFORMRESPONSE_H
