// Generated by gencpp from file aruco_service/PublishTablePointsRequest.msg
// DO NOT EDIT!


#ifndef ARUCO_SERVICE_MESSAGE_PUBLISHTABLEPOINTSREQUEST_H
#define ARUCO_SERVICE_MESSAGE_PUBLISHTABLEPOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_service
{
template <class ContainerAllocator>
struct PublishTablePointsRequest_
{
  typedef PublishTablePointsRequest_<ContainerAllocator> Type;

  PublishTablePointsRequest_()
    : table(0)  {
    }
  PublishTablePointsRequest_(const ContainerAllocator& _alloc)
    : table(0)  {
  (void)_alloc;
    }



   typedef int8_t _table_type;
  _table_type table;





  typedef boost::shared_ptr< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PublishTablePointsRequest_

typedef ::aruco_service::PublishTablePointsRequest_<std::allocator<void> > PublishTablePointsRequest;

typedef boost::shared_ptr< ::aruco_service::PublishTablePointsRequest > PublishTablePointsRequestPtr;
typedef boost::shared_ptr< ::aruco_service::PublishTablePointsRequest const> PublishTablePointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator1> & lhs, const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.table == rhs.table;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator1> & lhs, const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aruco_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c62310621d06b36148900c9fb5e61f3a";
  }

  static const char* value(const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc62310621d06b361ULL;
  static const uint64_t static_value2 = 0x48900c9fb5e61f3aULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_service/PublishTablePointsRequest";
  }

  static const char* value(const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 table\n"
;
  }

  static const char* value(const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.table);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PublishTablePointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_service::PublishTablePointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_service::PublishTablePointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "table: ";
    Printer<int8_t>::stream(s, indent + "  ", v.table);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_SERVICE_MESSAGE_PUBLISHTABLEPOINTSREQUEST_H
