// Generated by gencpp from file aruco_service/SaveNavigationPoint.msg
// DO NOT EDIT!


#ifndef ARUCO_SERVICE_MESSAGE_SAVENAVIGATIONPOINT_H
#define ARUCO_SERVICE_MESSAGE_SAVENAVIGATIONPOINT_H

#include <ros/service_traits.h>


#include <aruco_service/SaveNavigationPointRequest.h>
#include <aruco_service/SaveNavigationPointResponse.h>


namespace aruco_service
{

struct SaveNavigationPoint
{

typedef SaveNavigationPointRequest Request;
typedef SaveNavigationPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveNavigationPoint
} // namespace aruco_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aruco_service::SaveNavigationPoint > {
  static const char* value()
  {
    return "4eaecc5d02ae2f2661dfa53121841fde";
  }

  static const char* value(const ::aruco_service::SaveNavigationPoint&) { return value(); }
};

template<>
struct DataType< ::aruco_service::SaveNavigationPoint > {
  static const char* value()
  {
    return "aruco_service/SaveNavigationPoint";
  }

  static const char* value(const ::aruco_service::SaveNavigationPoint&) { return value(); }
};


// service_traits::MD5Sum< ::aruco_service::SaveNavigationPointRequest> should match
// service_traits::MD5Sum< ::aruco_service::SaveNavigationPoint >
template<>
struct MD5Sum< ::aruco_service::SaveNavigationPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_service::SaveNavigationPoint >::value();
  }
  static const char* value(const ::aruco_service::SaveNavigationPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_service::SaveNavigationPointRequest> should match
// service_traits::DataType< ::aruco_service::SaveNavigationPoint >
template<>
struct DataType< ::aruco_service::SaveNavigationPointRequest>
{
  static const char* value()
  {
    return DataType< ::aruco_service::SaveNavigationPoint >::value();
  }
  static const char* value(const ::aruco_service::SaveNavigationPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aruco_service::SaveNavigationPointResponse> should match
// service_traits::MD5Sum< ::aruco_service::SaveNavigationPoint >
template<>
struct MD5Sum< ::aruco_service::SaveNavigationPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_service::SaveNavigationPoint >::value();
  }
  static const char* value(const ::aruco_service::SaveNavigationPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_service::SaveNavigationPointResponse> should match
// service_traits::DataType< ::aruco_service::SaveNavigationPoint >
template<>
struct DataType< ::aruco_service::SaveNavigationPointResponse>
{
  static const char* value()
  {
    return DataType< ::aruco_service::SaveNavigationPoint >::value();
  }
  static const char* value(const ::aruco_service::SaveNavigationPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARUCO_SERVICE_MESSAGE_SAVENAVIGATIONPOINT_H
