(cl:defpackage lasr_dialogflow-srv
  (:use )
  (:export
   "DIALOGFLOWAUDIO"
   "<DIALOGFLOWAUDIO-REQUEST>"
   "DIALOGFLOWAUDIO-REQUEST"
   "<DIALOGFLOWAUDIO-RESPONSE>"
   "DIALOGFLOWAUDIO-RESPONSE"
   "DIALOGFLOWTEXT"
   "<DIALOGFLOWTEXT-REQUEST>"
   "DIALOGFLOWTEXT-REQUEST"
   "<DIALOGFLOWTEXT-RESPONSE>"
   "DIALOGFLOWTEXT-RESPONSE"
  ))

