// Generated by gencpp from file lasr_dialogflow/DialogflowAudioResponse.msg
// DO NOT EDIT!


#ifndef LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWAUDIORESPONSE_H
#define LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWAUDIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/Bool.h>

namespace lasr_dialogflow
{
template <class ContainerAllocator>
struct DialogflowAudioResponse_
{
  typedef DialogflowAudioResponse_<ContainerAllocator> Type;

  DialogflowAudioResponse_()
    : result()
    , success()  {
    }
  DialogflowAudioResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _result_type;
  _result_type result;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DialogflowAudioResponse_

typedef ::lasr_dialogflow::DialogflowAudioResponse_<std::allocator<void> > DialogflowAudioResponse;

typedef boost::shared_ptr< ::lasr_dialogflow::DialogflowAudioResponse > DialogflowAudioResponsePtr;
typedef boost::shared_ptr< ::lasr_dialogflow::DialogflowAudioResponse const> DialogflowAudioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator1> & lhs, const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator1> & lhs, const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_dialogflow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0800494afb8b2c91f943cf1d38c7b64";
  }

  static const char* value(const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0800494afb8b2c9ULL;
  static const uint64_t static_value2 = 0x1f943cf1d38c7b64ULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_dialogflow/DialogflowAudioResponse";
  }

  static const char* value(const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String result\n"
"std_msgs/Bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogflowAudioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_dialogflow::DialogflowAudioResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWAUDIORESPONSE_H
