// Generated by gencpp from file lasr_dialogflow/DialogflowText.msg
// DO NOT EDIT!


#ifndef LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWTEXT_H
#define LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWTEXT_H

#include <ros/service_traits.h>


#include <lasr_dialogflow/DialogflowTextRequest.h>
#include <lasr_dialogflow/DialogflowTextResponse.h>


namespace lasr_dialogflow
{

struct DialogflowText
{

typedef DialogflowTextRequest Request;
typedef DialogflowTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DialogflowText
} // namespace lasr_dialogflow


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lasr_dialogflow::DialogflowText > {
  static const char* value()
  {
    return "b626d0b32e2760daee50a75d7d83566b";
  }

  static const char* value(const ::lasr_dialogflow::DialogflowText&) { return value(); }
};

template<>
struct DataType< ::lasr_dialogflow::DialogflowText > {
  static const char* value()
  {
    return "lasr_dialogflow/DialogflowText";
  }

  static const char* value(const ::lasr_dialogflow::DialogflowText&) { return value(); }
};


// service_traits::MD5Sum< ::lasr_dialogflow::DialogflowTextRequest> should match
// service_traits::MD5Sum< ::lasr_dialogflow::DialogflowText >
template<>
struct MD5Sum< ::lasr_dialogflow::DialogflowTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_dialogflow::DialogflowText >::value();
  }
  static const char* value(const ::lasr_dialogflow::DialogflowTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_dialogflow::DialogflowTextRequest> should match
// service_traits::DataType< ::lasr_dialogflow::DialogflowText >
template<>
struct DataType< ::lasr_dialogflow::DialogflowTextRequest>
{
  static const char* value()
  {
    return DataType< ::lasr_dialogflow::DialogflowText >::value();
  }
  static const char* value(const ::lasr_dialogflow::DialogflowTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lasr_dialogflow::DialogflowTextResponse> should match
// service_traits::MD5Sum< ::lasr_dialogflow::DialogflowText >
template<>
struct MD5Sum< ::lasr_dialogflow::DialogflowTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_dialogflow::DialogflowText >::value();
  }
  static const char* value(const ::lasr_dialogflow::DialogflowTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_dialogflow::DialogflowTextResponse> should match
// service_traits::DataType< ::lasr_dialogflow::DialogflowText >
template<>
struct DataType< ::lasr_dialogflow::DialogflowTextResponse>
{
  static const char* value()
  {
    return DataType< ::lasr_dialogflow::DialogflowText >::value();
  }
  static const char* value(const ::lasr_dialogflow::DialogflowTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASR_DIALOGFLOW_MESSAGE_DIALOGFLOWTEXT_H
