(cl:defpackage lasr_shapely-srv
  (:use )
  (:export
   "POINTINPOLYGON2D"
   "<POINTINPOLYGON2D-REQUEST>"
   "POINTINPOLYGON2D-REQUEST"
   "<POINTINPOLYGON2D-RESPONSE>"
   "POINTINPOLYGON2D-RESPONSE"
   "POINTSINPOLYGON2D"
   "<POINTSINPOLYGON2D-REQUEST>"
   "POINTSINPOLYGON2D-REQUEST"
   "<POINTSINPOLYGON2D-RESPONSE>"
   "POINTSINPOLYGON2D-RESPONSE"
  ))

