// Generated by gencpp from file lasr_shapely/PointsInPolygon2DRequest.msg
// DO NOT EDIT!


#ifndef LASR_SHAPELY_MESSAGE_POINTSINPOLYGON2DREQUEST_H
#define LASR_SHAPELY_MESSAGE_POINTSINPOLYGON2DREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lasr_shapely
{
template <class ContainerAllocator>
struct PointsInPolygon2DRequest_
{
  typedef PointsInPolygon2DRequest_<ContainerAllocator> Type;

  PointsInPolygon2DRequest_()
    : polygon()
    , points()  {
    }
  PointsInPolygon2DRequest_(const ContainerAllocator& _alloc)
    : polygon(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _polygon_type;
  _polygon_type polygon;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointsInPolygon2DRequest_

typedef ::lasr_shapely::PointsInPolygon2DRequest_<std::allocator<void> > PointsInPolygon2DRequest;

typedef boost::shared_ptr< ::lasr_shapely::PointsInPolygon2DRequest > PointsInPolygon2DRequestPtr;
typedef boost::shared_ptr< ::lasr_shapely::PointsInPolygon2DRequest const> PointsInPolygon2DRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator1> & lhs, const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator2> & rhs)
{
  return lhs.polygon == rhs.polygon &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator1> & lhs, const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_shapely

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6ff8b332b345b715cefe1aeadd95cef";
  }

  static const char* value(const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6ff8b332b345b71ULL;
  static const uint64_t static_value2 = 0x5cefe1aeadd95cefULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_shapely/PointsInPolygon2DRequest";
  }

  static const char* value(const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 1D-array of ordered pairs of points (connected by edge) that define the polygon\n"
"float32[] polygon\n"
"# 1D-array of pairs of points\n"
"float32[] points\n"
;
  }

  static const char* value(const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.polygon);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointsInPolygon2DRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_shapely::PointsInPolygon2DRequest_<ContainerAllocator>& v)
  {
    s << indent << "polygon[]" << std::endl;
    for (size_t i = 0; i < v.polygon.size(); ++i)
    {
      s << indent << "  polygon[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.polygon[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_SHAPELY_MESSAGE_POINTSINPOLYGON2DREQUEST_H
