// Generated by gencpp from file tiago_controllers/ArmTorsoPos.msg
// DO NOT EDIT!


#ifndef TIAGO_CONTROLLERS_MESSAGE_ARMTORSOPOS_H
#define TIAGO_CONTROLLERS_MESSAGE_ARMTORSOPOS_H

#include <ros/service_traits.h>


#include <tiago_controllers/ArmTorsoPosRequest.h>
#include <tiago_controllers/ArmTorsoPosResponse.h>


namespace tiago_controllers
{

struct ArmTorsoPos
{

typedef ArmTorsoPosRequest Request;
typedef ArmTorsoPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmTorsoPos
} // namespace tiago_controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_controllers::ArmTorsoPos > {
  static const char* value()
  {
    return "3f0dca51556e205f687af18e1b29aeb3";
  }

  static const char* value(const ::tiago_controllers::ArmTorsoPos&) { return value(); }
};

template<>
struct DataType< ::tiago_controllers::ArmTorsoPos > {
  static const char* value()
  {
    return "tiago_controllers/ArmTorsoPos";
  }

  static const char* value(const ::tiago_controllers::ArmTorsoPos&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_controllers::ArmTorsoPosRequest> should match
// service_traits::MD5Sum< ::tiago_controllers::ArmTorsoPos >
template<>
struct MD5Sum< ::tiago_controllers::ArmTorsoPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_controllers::ArmTorsoPos >::value();
  }
  static const char* value(const ::tiago_controllers::ArmTorsoPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_controllers::ArmTorsoPosRequest> should match
// service_traits::DataType< ::tiago_controllers::ArmTorsoPos >
template<>
struct DataType< ::tiago_controllers::ArmTorsoPosRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_controllers::ArmTorsoPos >::value();
  }
  static const char* value(const ::tiago_controllers::ArmTorsoPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_controllers::ArmTorsoPosResponse> should match
// service_traits::MD5Sum< ::tiago_controllers::ArmTorsoPos >
template<>
struct MD5Sum< ::tiago_controllers::ArmTorsoPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_controllers::ArmTorsoPos >::value();
  }
  static const char* value(const ::tiago_controllers::ArmTorsoPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_controllers::ArmTorsoPosResponse> should match
// service_traits::DataType< ::tiago_controllers::ArmTorsoPos >
template<>
struct DataType< ::tiago_controllers::ArmTorsoPosResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_controllers::ArmTorsoPos >::value();
  }
  static const char* value(const ::tiago_controllers::ArmTorsoPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_CONTROLLERS_MESSAGE_ARMTORSOPOS_H
