(cl:defpackage interaction_module-srv
  (:use )
  (:export
   "AUDIOANDTEXTINTERACTION"
   "<AUDIOANDTEXTINTERACTION-REQUEST>"
   "AUDIOANDTEXTINTERACTION-REQUEST"
   "<AUDIOANDTEXTINTERACTION-RESPONSE>"
   "AUDIOANDTEXTINTERACTION-RESPONSE"
  ))

