#!/usr/bin/env bash

if [ "TRUE" = "TRUE" ]; then
	exec /home/k21066336/tiago_public_ws/devel/.private/lasr_vision_yolov8/share/lasr_vision_yolov8/venv/bin/python - "$@" <<- EOF
	import re
	import sys

	from setproctitle import setproctitle

	program_path = "/home/k21066336/tiago_public_ws/src/lasr_vision_yolov8/nodes/service"
	setproctitle(' '.join([program_path] + sys.argv[1:]))
	exec(open(program_path).read())
	EOF
else
	exec /home/k21066336/tiago_public_ws/devel/.private/lasr_vision_yolov8/share/lasr_vision_yolov8/venv/bin/python /home/k21066336/tiago_public_ws/src/lasr_vision_yolov8/nodes/service "$@"
fi
