// Generated by gencpp from file listen_module/DialogListenResponse.msg
// DO NOT EDIT!


#ifndef LISTEN_MODULE_MESSAGE_DIALOGLISTENRESPONSE_H
#define LISTEN_MODULE_MESSAGE_DIALOGLISTENRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace listen_module
{
template <class ContainerAllocator>
struct DialogListenResponse_
{
  typedef DialogListenResponse_<ContainerAllocator> Type;

  DialogListenResponse_()
    : status(false)
    , result()  {
    }
  DialogListenResponse_(const ContainerAllocator& _alloc)
    : status(false)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::listen_module::DialogListenResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::listen_module::DialogListenResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DialogListenResponse_

typedef ::listen_module::DialogListenResponse_<std::allocator<void> > DialogListenResponse;

typedef boost::shared_ptr< ::listen_module::DialogListenResponse > DialogListenResponsePtr;
typedef boost::shared_ptr< ::listen_module::DialogListenResponse const> DialogListenResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::listen_module::DialogListenResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::listen_module::DialogListenResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::listen_module::DialogListenResponse_<ContainerAllocator1> & lhs, const ::listen_module::DialogListenResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::listen_module::DialogListenResponse_<ContainerAllocator1> & lhs, const ::listen_module::DialogListenResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace listen_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::listen_module::DialogListenResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::listen_module::DialogListenResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::listen_module::DialogListenResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::listen_module::DialogListenResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::listen_module::DialogListenResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::listen_module::DialogListenResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::listen_module::DialogListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ef8cb8c27fbede28b0373c7f7c318e1";
  }

  static const char* value(const ::listen_module::DialogListenResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ef8cb8c27fbede2ULL;
  static const uint64_t static_value2 = 0x8b0373c7f7c318e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::listen_module::DialogListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "listen_module/DialogListenResponse";
  }

  static const char* value(const ::listen_module::DialogListenResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::listen_module::DialogListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"string result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::listen_module::DialogListenResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::listen_module::DialogListenResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogListenResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::listen_module::DialogListenResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::listen_module::DialogListenResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LISTEN_MODULE_MESSAGE_DIALOGLISTENRESPONSE_H
