// Generated by gencpp from file lasr_interaction_server/SpeechInteraction.msg
// DO NOT EDIT!


#ifndef LASR_INTERACTION_SERVER_MESSAGE_SPEECHINTERACTION_H
#define LASR_INTERACTION_SERVER_MESSAGE_SPEECHINTERACTION_H

#include <ros/service_traits.h>


#include <lasr_interaction_server/SpeechInteractionRequest.h>
#include <lasr_interaction_server/SpeechInteractionResponse.h>


namespace lasr_interaction_server
{

struct SpeechInteraction
{

typedef SpeechInteractionRequest Request;
typedef SpeechInteractionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechInteraction
} // namespace lasr_interaction_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lasr_interaction_server::SpeechInteraction > {
  static const char* value()
  {
    return "c6778e75ee863a7048845ef167f478f5";
  }

  static const char* value(const ::lasr_interaction_server::SpeechInteraction&) { return value(); }
};

template<>
struct DataType< ::lasr_interaction_server::SpeechInteraction > {
  static const char* value()
  {
    return "lasr_interaction_server/SpeechInteraction";
  }

  static const char* value(const ::lasr_interaction_server::SpeechInteraction&) { return value(); }
};


// service_traits::MD5Sum< ::lasr_interaction_server::SpeechInteractionRequest> should match
// service_traits::MD5Sum< ::lasr_interaction_server::SpeechInteraction >
template<>
struct MD5Sum< ::lasr_interaction_server::SpeechInteractionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_interaction_server::SpeechInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::SpeechInteractionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_interaction_server::SpeechInteractionRequest> should match
// service_traits::DataType< ::lasr_interaction_server::SpeechInteraction >
template<>
struct DataType< ::lasr_interaction_server::SpeechInteractionRequest>
{
  static const char* value()
  {
    return DataType< ::lasr_interaction_server::SpeechInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::SpeechInteractionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lasr_interaction_server::SpeechInteractionResponse> should match
// service_traits::MD5Sum< ::lasr_interaction_server::SpeechInteraction >
template<>
struct MD5Sum< ::lasr_interaction_server::SpeechInteractionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_interaction_server::SpeechInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::SpeechInteractionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_interaction_server::SpeechInteractionResponse> should match
// service_traits::DataType< ::lasr_interaction_server::SpeechInteraction >
template<>
struct DataType< ::lasr_interaction_server::SpeechInteractionResponse>
{
  static const char* value()
  {
    return DataType< ::lasr_interaction_server::SpeechInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::SpeechInteractionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASR_INTERACTION_SERVER_MESSAGE_SPEECHINTERACTION_H
