// Generated by gencpp from file lasr_interaction_server/TextInteraction.msg
// DO NOT EDIT!


#ifndef LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTION_H
#define LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTION_H

#include <ros/service_traits.h>


#include <lasr_interaction_server/TextInteractionRequest.h>
#include <lasr_interaction_server/TextInteractionResponse.h>


namespace lasr_interaction_server
{

struct TextInteraction
{

typedef TextInteractionRequest Request;
typedef TextInteractionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TextInteraction
} // namespace lasr_interaction_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lasr_interaction_server::TextInteraction > {
  static const char* value()
  {
    return "b626d0b32e2760daee50a75d7d83566b";
  }

  static const char* value(const ::lasr_interaction_server::TextInteraction&) { return value(); }
};

template<>
struct DataType< ::lasr_interaction_server::TextInteraction > {
  static const char* value()
  {
    return "lasr_interaction_server/TextInteraction";
  }

  static const char* value(const ::lasr_interaction_server::TextInteraction&) { return value(); }
};


// service_traits::MD5Sum< ::lasr_interaction_server::TextInteractionRequest> should match
// service_traits::MD5Sum< ::lasr_interaction_server::TextInteraction >
template<>
struct MD5Sum< ::lasr_interaction_server::TextInteractionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_interaction_server::TextInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::TextInteractionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_interaction_server::TextInteractionRequest> should match
// service_traits::DataType< ::lasr_interaction_server::TextInteraction >
template<>
struct DataType< ::lasr_interaction_server::TextInteractionRequest>
{
  static const char* value()
  {
    return DataType< ::lasr_interaction_server::TextInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::TextInteractionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lasr_interaction_server::TextInteractionResponse> should match
// service_traits::MD5Sum< ::lasr_interaction_server::TextInteraction >
template<>
struct MD5Sum< ::lasr_interaction_server::TextInteractionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_interaction_server::TextInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::TextInteractionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_interaction_server::TextInteractionResponse> should match
// service_traits::DataType< ::lasr_interaction_server::TextInteraction >
template<>
struct DataType< ::lasr_interaction_server::TextInteractionResponse>
{
  static const char* value()
  {
    return DataType< ::lasr_interaction_server::TextInteraction >::value();
  }
  static const char* value(const ::lasr_interaction_server::TextInteractionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTION_H
