// Generated by gencpp from file lasr_interaction_server/TextInteractionRequest.msg
// DO NOT EDIT!


#ifndef LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTIONREQUEST_H
#define LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace lasr_interaction_server
{
template <class ContainerAllocator>
struct TextInteractionRequest_
{
  typedef TextInteractionRequest_<ContainerAllocator> Type;

  TextInteractionRequest_()
    : task()
    , action()
    , query_text()  {
    }
  TextInteractionRequest_(const ContainerAllocator& _alloc)
    : task(_alloc)
    , action(_alloc)
    , query_text(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _task_type;
  _task_type task;

   typedef  ::std_msgs::String_<ContainerAllocator>  _action_type;
  _action_type action;

   typedef  ::std_msgs::String_<ContainerAllocator>  _query_text_type;
  _query_text_type query_text;





  typedef boost::shared_ptr< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TextInteractionRequest_

typedef ::lasr_interaction_server::TextInteractionRequest_<std::allocator<void> > TextInteractionRequest;

typedef boost::shared_ptr< ::lasr_interaction_server::TextInteractionRequest > TextInteractionRequestPtr;
typedef boost::shared_ptr< ::lasr_interaction_server::TextInteractionRequest const> TextInteractionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator1> & lhs, const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task &&
    lhs.action == rhs.action &&
    lhs.query_text == rhs.query_text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator1> & lhs, const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_interaction_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9cc91f0db9a356c6f5e739901dcb1a3";
  }

  static const char* value(const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9cc91f0db9a356cULL;
  static const uint64_t static_value2 = 0x6f5e739901dcb1a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_interaction_server/TextInteractionRequest";
  }

  static const char* value(const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String task\n"
"std_msgs/String action\n"
"std_msgs/String query_text\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
      stream.next(m.action);
      stream.next(m.query_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TextInteractionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_interaction_server::TextInteractionRequest_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.task);
    s << indent << "action: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.action);
    s << indent << "query_text: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.query_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_INTERACTION_SERVER_MESSAGE_TEXTINTERACTIONREQUEST_H
