(cl:defpackage aruco_service-srv
  (:use )
  (:export
   "GENERATETABLECUBOID"
   "<GENERATETABLECUBOID-REQUEST>"
   "GENERATETABLECUBOID-REQUEST"
   "<GENERATETABLECUBOID-RESPONSE>"
   "GENERATETABLECUBOID-RESPONSE"
   "PUBLISHTABLEPOINTS"
   "<PUBLISHTABLEPOINTS-REQUEST>"
   "PUBLISHTABLEPOINTS-REQUEST"
   "<PUBLISHTABLEPOINTS-RESPONSE>"
   "PUBLISHTABLEPOINTS-RESPONSE"
   "SAVENAVIGATIONPOINT"
   "<SAVENAVIGATIONPOINT-REQUEST>"
   "SAVENAVIGATIONPOINT-REQUEST"
   "<SAVENAVIGATIONPOINT-RESPONSE>"
   "SAVENAVIGATIONPOINT-RESPONSE"
  ))

