(cl:defpackage lasr_vision_msgs-srv
  (:use )
  (:export
   "BODYPIXDETECTION"
   "<BODYPIXDETECTION-REQUEST>"
   "BODYPIXDETECTION-REQUEST"
   "<BODYPIXDETECTION-RESPONSE>"
   "BODYPIXDETECTION-RESPONSE"
   "RECOGNISE"
   "<RECOGNISE-REQUEST>"
   "RECOGNISE-REQUEST"
   "<RECOGNISE-RESPONSE>"
   "RECOGNISE-RESPONSE"
   "TORCHFACEFEATUREDETECTION"
   "<TORCHFACEFEATUREDETECTION-REQUEST>"
   "TORCHFACEFEATUREDETECTION-REQUEST"
   "<TORCHFACEFEATUREDETECTION-RESPONSE>"
   "TORCHFACEFEATUREDETECTION-RESPONSE"
   "YOLODETECTION"
   "<YOLODETECTION-REQUEST>"
   "YOLODETECTION-REQUEST"
   "<YOLODETECTION-RESPONSE>"
   "YOLODETECTION-RESPONSE"
  ))

