// Generated by gencpp from file face_detection/FaceDetectionRequest.msg
// DO NOT EDIT!


#ifndef FACE_DETECTION_MESSAGE_FACEDETECTIONREQUEST_H
#define FACE_DETECTION_MESSAGE_FACEDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace face_detection
{
template <class ContainerAllocator>
struct FaceDetectionRequest_
{
  typedef FaceDetectionRequest_<ContainerAllocator> Type;

  FaceDetectionRequest_()
    : image_raw()  {
    }
  FaceDetectionRequest_(const ContainerAllocator& _alloc)
    : image_raw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_raw_type;
  _image_raw_type image_raw;





  typedef boost::shared_ptr< ::face_detection::FaceDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_detection::FaceDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectionRequest_

typedef ::face_detection::FaceDetectionRequest_<std::allocator<void> > FaceDetectionRequest;

typedef boost::shared_ptr< ::face_detection::FaceDetectionRequest > FaceDetectionRequestPtr;
typedef boost::shared_ptr< ::face_detection::FaceDetectionRequest const> FaceDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_detection::FaceDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::face_detection::FaceDetectionRequest_<ContainerAllocator1> & lhs, const ::face_detection::FaceDetectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_raw == rhs.image_raw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::face_detection::FaceDetectionRequest_<ContainerAllocator1> & lhs, const ::face_detection::FaceDetectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace face_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detection::FaceDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detection::FaceDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detection::FaceDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cc2871aa67733f0f532f04e505ef0dd";
  }

  static const char* value(const ::face_detection::FaceDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cc2871aa67733f0ULL;
  static const uint64_t static_value2 = 0xf532f04e505ef0ddULL;
};

template<class ContainerAllocator>
struct DataType< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_detection/FaceDetectionRequest";
  }

  static const char* value(const ::face_detection::FaceDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image_raw\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::face_detection::FaceDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_raw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_detection::FaceDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::face_detection::FaceDetectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_raw: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_raw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FACE_DETECTION_MESSAGE_FACEDETECTIONREQUEST_H
