// Generated by gencpp from file object_interest_tracking/Tdr.msg
// DO NOT EDIT!


#ifndef OBJECT_INTEREST_TRACKING_MESSAGE_TDR_H
#define OBJECT_INTEREST_TRACKING_MESSAGE_TDR_H

#include <ros/service_traits.h>


#include <object_interest_tracking/TdrRequest.h>
#include <object_interest_tracking/TdrResponse.h>


namespace object_interest_tracking
{

struct Tdr
{

typedef TdrRequest Request;
typedef TdrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tdr
} // namespace object_interest_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_interest_tracking::Tdr > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::object_interest_tracking::Tdr&) { return value(); }
};

template<>
struct DataType< ::object_interest_tracking::Tdr > {
  static const char* value()
  {
    return "object_interest_tracking/Tdr";
  }

  static const char* value(const ::object_interest_tracking::Tdr&) { return value(); }
};


// service_traits::MD5Sum< ::object_interest_tracking::TdrRequest> should match
// service_traits::MD5Sum< ::object_interest_tracking::Tdr >
template<>
struct MD5Sum< ::object_interest_tracking::TdrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_interest_tracking::Tdr >::value();
  }
  static const char* value(const ::object_interest_tracking::TdrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_interest_tracking::TdrRequest> should match
// service_traits::DataType< ::object_interest_tracking::Tdr >
template<>
struct DataType< ::object_interest_tracking::TdrRequest>
{
  static const char* value()
  {
    return DataType< ::object_interest_tracking::Tdr >::value();
  }
  static const char* value(const ::object_interest_tracking::TdrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_interest_tracking::TdrResponse> should match
// service_traits::MD5Sum< ::object_interest_tracking::Tdr >
template<>
struct MD5Sum< ::object_interest_tracking::TdrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_interest_tracking::Tdr >::value();
  }
  static const char* value(const ::object_interest_tracking::TdrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_interest_tracking::TdrResponse> should match
// service_traits::DataType< ::object_interest_tracking::Tdr >
template<>
struct DataType< ::object_interest_tracking::TdrResponse>
{
  static const char* value()
  {
    return DataType< ::object_interest_tracking::Tdr >::value();
  }
  static const char* value(const ::object_interest_tracking::TdrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_INTEREST_TRACKING_MESSAGE_TDR_H
