// Generated by gencpp from file graph_room_navigation/AddRoomResponse.msg
// DO NOT EDIT!


#ifndef GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOMRESPONSE_H
#define GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_room_navigation
{
template <class ContainerAllocator>
struct AddRoomResponse_
{
  typedef AddRoomResponse_<ContainerAllocator> Type;

  AddRoomResponse_()
    : success(false)  {
    }
  AddRoomResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddRoomResponse_

typedef ::graph_room_navigation::AddRoomResponse_<std::allocator<void> > AddRoomResponse;

typedef boost::shared_ptr< ::graph_room_navigation::AddRoomResponse > AddRoomResponsePtr;
typedef boost::shared_ptr< ::graph_room_navigation::AddRoomResponse const> AddRoomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator1> & lhs, const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator1> & lhs, const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_room_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_room_navigation/AddRoomResponse";
  }

  static const char* value(const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddRoomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_room_navigation::AddRoomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_room_navigation::AddRoomResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOMRESPONSE_H
