// Generated by gencpp from file graph_room_navigation/AddRoom.msg
// DO NOT EDIT!


#ifndef GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOM_H
#define GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOM_H

#include <ros/service_traits.h>


#include <graph_room_navigation/AddRoomRequest.h>
#include <graph_room_navigation/AddRoomResponse.h>


namespace graph_room_navigation
{

struct AddRoom
{

typedef AddRoomRequest Request;
typedef AddRoomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddRoom
} // namespace graph_room_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_room_navigation::AddRoom > {
  static const char* value()
  {
    return "a8afbfcd27d4409c8fc3633455b491d0";
  }

  static const char* value(const ::graph_room_navigation::AddRoom&) { return value(); }
};

template<>
struct DataType< ::graph_room_navigation::AddRoom > {
  static const char* value()
  {
    return "graph_room_navigation/AddRoom";
  }

  static const char* value(const ::graph_room_navigation::AddRoom&) { return value(); }
};


// service_traits::MD5Sum< ::graph_room_navigation::AddRoomRequest> should match
// service_traits::MD5Sum< ::graph_room_navigation::AddRoom >
template<>
struct MD5Sum< ::graph_room_navigation::AddRoomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_room_navigation::AddRoom >::value();
  }
  static const char* value(const ::graph_room_navigation::AddRoomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_room_navigation::AddRoomRequest> should match
// service_traits::DataType< ::graph_room_navigation::AddRoom >
template<>
struct DataType< ::graph_room_navigation::AddRoomRequest>
{
  static const char* value()
  {
    return DataType< ::graph_room_navigation::AddRoom >::value();
  }
  static const char* value(const ::graph_room_navigation::AddRoomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_room_navigation::AddRoomResponse> should match
// service_traits::MD5Sum< ::graph_room_navigation::AddRoom >
template<>
struct MD5Sum< ::graph_room_navigation::AddRoomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_room_navigation::AddRoom >::value();
  }
  static const char* value(const ::graph_room_navigation::AddRoomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_room_navigation::AddRoomResponse> should match
// service_traits::DataType< ::graph_room_navigation::AddRoom >
template<>
struct DataType< ::graph_room_navigation::AddRoomResponse>
{
  static const char* value()
  {
    return DataType< ::graph_room_navigation::AddRoom >::value();
  }
  static const char* value(const ::graph_room_navigation::AddRoomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_ROOM_NAVIGATION_MESSAGE_ADDROOM_H
