// Generated by gencpp from file graph_room_navigation/PlanToPointResponse.msg
// DO NOT EDIT!


#ifndef GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINTRESPONSE_H
#define GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace graph_room_navigation
{
template <class ContainerAllocator>
struct PlanToPointResponse_
{
  typedef PlanToPointResponse_<ContainerAllocator> Type;

  PlanToPointResponse_()
    : points()
    , success(false)  {
    }
  PlanToPointResponse_(const ContainerAllocator& _alloc)
    : points(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanToPointResponse_

typedef ::graph_room_navigation::PlanToPointResponse_<std::allocator<void> > PlanToPointResponse;

typedef boost::shared_ptr< ::graph_room_navigation::PlanToPointResponse > PlanToPointResponsePtr;
typedef boost::shared_ptr< ::graph_room_navigation::PlanToPointResponse const> PlanToPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator1> & lhs, const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator1> & lhs, const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_room_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "439a0fe22df86319f00b16d4618d7483";
  }

  static const char* value(const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x439a0fe22df86319ULL;
  static const uint64_t static_value2 = 0xf00b16d4618d7483ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_room_navigation/PlanToPointResponse";
  }

  static const char* value(const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanToPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_room_navigation::PlanToPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINTRESPONSE_H
