// Generated by gencpp from file graph_room_navigation/PlanToPoint.msg
// DO NOT EDIT!


#ifndef GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINT_H
#define GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINT_H

#include <ros/service_traits.h>


#include <graph_room_navigation/PlanToPointRequest.h>
#include <graph_room_navigation/PlanToPointResponse.h>


namespace graph_room_navigation
{

struct PlanToPoint
{

typedef PlanToPointRequest Request;
typedef PlanToPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanToPoint
} // namespace graph_room_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_room_navigation::PlanToPoint > {
  static const char* value()
  {
    return "b4e6b6656aa551fdc5d5b4c72e95d532";
  }

  static const char* value(const ::graph_room_navigation::PlanToPoint&) { return value(); }
};

template<>
struct DataType< ::graph_room_navigation::PlanToPoint > {
  static const char* value()
  {
    return "graph_room_navigation/PlanToPoint";
  }

  static const char* value(const ::graph_room_navigation::PlanToPoint&) { return value(); }
};


// service_traits::MD5Sum< ::graph_room_navigation::PlanToPointRequest> should match
// service_traits::MD5Sum< ::graph_room_navigation::PlanToPoint >
template<>
struct MD5Sum< ::graph_room_navigation::PlanToPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_room_navigation::PlanToPoint >::value();
  }
  static const char* value(const ::graph_room_navigation::PlanToPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_room_navigation::PlanToPointRequest> should match
// service_traits::DataType< ::graph_room_navigation::PlanToPoint >
template<>
struct DataType< ::graph_room_navigation::PlanToPointRequest>
{
  static const char* value()
  {
    return DataType< ::graph_room_navigation::PlanToPoint >::value();
  }
  static const char* value(const ::graph_room_navigation::PlanToPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_room_navigation::PlanToPointResponse> should match
// service_traits::MD5Sum< ::graph_room_navigation::PlanToPoint >
template<>
struct MD5Sum< ::graph_room_navigation::PlanToPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_room_navigation::PlanToPoint >::value();
  }
  static const char* value(const ::graph_room_navigation::PlanToPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_room_navigation::PlanToPointResponse> should match
// service_traits::DataType< ::graph_room_navigation::PlanToPoint >
template<>
struct DataType< ::graph_room_navigation::PlanToPointResponse>
{
  static const char* value()
  {
    return DataType< ::graph_room_navigation::PlanToPoint >::value();
  }
  static const char* value(const ::graph_room_navigation::PlanToPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_ROOM_NAVIGATION_MESSAGE_PLANTOPOINT_H
