// Generated by gencpp from file lasr_object_detection_yolo/YoloDetectionRequest.msg
// DO NOT EDIT!


#ifndef LASR_OBJECT_DETECTION_YOLO_MESSAGE_YOLODETECTIONREQUEST_H
#define LASR_OBJECT_DETECTION_YOLO_MESSAGE_YOLODETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace lasr_object_detection_yolo
{
template <class ContainerAllocator>
struct YoloDetectionRequest_
{
  typedef YoloDetectionRequest_<ContainerAllocator> Type;

  YoloDetectionRequest_()
    : image_raw()
    , dataset()
    , confidence(0.0)
    , nms(0.0)  {
    }
  YoloDetectionRequest_(const ContainerAllocator& _alloc)
    : image_raw(_alloc)
    , dataset(_alloc)
    , confidence(0.0)
    , nms(0.0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_raw_type;
  _image_raw_type image_raw;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dataset_type;
  _dataset_type dataset;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _nms_type;
  _nms_type nms;





  typedef boost::shared_ptr< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetectionRequest_

typedef ::lasr_object_detection_yolo::YoloDetectionRequest_<std::allocator<void> > YoloDetectionRequest;

typedef boost::shared_ptr< ::lasr_object_detection_yolo::YoloDetectionRequest > YoloDetectionRequestPtr;
typedef boost::shared_ptr< ::lasr_object_detection_yolo::YoloDetectionRequest const> YoloDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator1> & lhs, const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_raw == rhs.image_raw &&
    lhs.dataset == rhs.dataset &&
    lhs.confidence == rhs.confidence &&
    lhs.nms == rhs.nms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator1> & lhs, const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_object_detection_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4de8906ec1c7e28a771d8bc815eb8ed";
  }

  static const char* value(const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4de8906ec1c7e28ULL;
  static const uint64_t static_value2 = 0xa771d8bc815eb8edULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_object_detection_yolo/YoloDetectionRequest";
  }

  static const char* value(const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image image_raw\n"
"string dataset\n"
"float32 confidence\n"
"float32 nms\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_raw);
      stream.next(m.dataset);
      stream.next(m.confidence);
      stream.next(m.nms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_object_detection_yolo::YoloDetectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_raw: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image_raw);
    s << indent << "dataset: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dataset);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "nms: ";
    Printer<float>::stream(s, indent + "  ", v.nms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_OBJECT_DETECTION_YOLO_MESSAGE_YOLODETECTIONREQUEST_H
