// Generated by gencpp from file lasr_vision_msgs/Detection.msg
// DO NOT EDIT!


#ifndef LASR_VISION_MSGS_MESSAGE_DETECTION_H
#define LASR_VISION_MSGS_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lasr_vision_msgs
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : name()
    , confidence(0.0)
    , xywh()
    , xyseg()  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , confidence(0.0)
    , xywh(_alloc)
    , xyseg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _xywh_type;
  _xywh_type xywh;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _xyseg_type;
  _xyseg_type xyseg;





  typedef boost::shared_ptr< ::lasr_vision_msgs::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_vision_msgs::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::lasr_vision_msgs::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::lasr_vision_msgs::Detection > DetectionPtr;
typedef boost::shared_ptr< ::lasr_vision_msgs::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_vision_msgs::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_vision_msgs::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_vision_msgs::Detection_<ContainerAllocator1> & lhs, const ::lasr_vision_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.confidence == rhs.confidence &&
    lhs.xywh == rhs.xywh &&
    lhs.xyseg == rhs.xyseg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_vision_msgs::Detection_<ContainerAllocator1> & lhs, const ::lasr_vision_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_vision_msgs::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_vision_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_vision_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61d9584ca7ba067a2cddb1ec142f3727";
  }

  static const char* value(const ::lasr_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61d9584ca7ba067aULL;
  static const uint64_t static_value2 = 0x2cddb1ec142f3727ULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_vision_msgs/Detection";
  }

  static const char* value(const ::lasr_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Detected Object Class\n"
"string name\n"
"\n"
"# How certain we are this is what we think it is\n"
"float32 confidence\n"
"\n"
"# Bounding box mask defined in pixel-space\n"
"int32[] xywh\n"
"\n"
"# Segmentation mask defined in pixel-space\n"
"#\n"
"# This will be empty if a segmentation model was not used\n"
"int32[] xyseg\n"
;
  }

  static const char* value(const ::lasr_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.confidence);
      stream.next(m.xywh);
      stream.next(m.xyseg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_vision_msgs::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_vision_msgs::Detection_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "xywh[]" << std::endl;
    for (size_t i = 0; i < v.xywh.size(); ++i)
    {
      s << indent << "  xywh[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.xywh[i]);
    }
    s << indent << "xyseg[]" << std::endl;
    for (size_t i = 0; i < v.xyseg.size(); ++i)
    {
      s << indent << "  xyseg[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.xyseg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_VISION_MSGS_MESSAGE_DETECTION_H
