// Generated by gencpp from file lasr_vision_msgs/RecogniseResponse.msg
// DO NOT EDIT!


#ifndef LASR_VISION_MSGS_MESSAGE_RECOGNISERESPONSE_H
#define LASR_VISION_MSGS_MESSAGE_RECOGNISERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lasr_vision_msgs/Detection.h>

namespace lasr_vision_msgs
{
template <class ContainerAllocator>
struct RecogniseResponse_
{
  typedef RecogniseResponse_<ContainerAllocator> Type;

  RecogniseResponse_()
    : detections()  {
    }
  RecogniseResponse_(const ContainerAllocator& _alloc)
    : detections(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lasr_vision_msgs::Detection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::lasr_vision_msgs::Detection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecogniseResponse_

typedef ::lasr_vision_msgs::RecogniseResponse_<std::allocator<void> > RecogniseResponse;

typedef boost::shared_ptr< ::lasr_vision_msgs::RecogniseResponse > RecogniseResponsePtr;
typedef boost::shared_ptr< ::lasr_vision_msgs::RecogniseResponse const> RecogniseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator1> & lhs, const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator1> & lhs, const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lasr_vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47659603d58e00dd450af638fbd3d117";
  }

  static const char* value(const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47659603d58e00ddULL;
  static const uint64_t static_value2 = 0x450af638fbd3d117ULL;
};

template<class ContainerAllocator>
struct DataType< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lasr_vision_msgs/RecogniseResponse";
  }

  static const char* value(const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Detections\n"
"lasr_vision_msgs/Detection[] detections\n"
"\n"
"\n"
"================================================================================\n"
"MSG: lasr_vision_msgs/Detection\n"
"# Detected Object Class\n"
"string name\n"
"\n"
"# How certain we are this is what we think it is\n"
"float32 confidence\n"
"\n"
"# Bounding box mask defined in pixel-space\n"
"int32[] xywh\n"
"\n"
"# Segmentation mask defined in pixel-space\n"
"#\n"
"# This will be empty if a segmentation model was not used\n"
"int32[] xyseg\n"
;
  }

  static const char* value(const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecogniseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lasr_vision_msgs::RecogniseResponse_<ContainerAllocator>& v)
  {
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lasr_vision_msgs::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASR_VISION_MSGS_MESSAGE_RECOGNISERESPONSE_H
