// Generated by gencpp from file lasr_vision_msgs/TorchFaceFeatureDetection.msg
// DO NOT EDIT!


#ifndef LASR_VISION_MSGS_MESSAGE_TORCHFACEFEATUREDETECTION_H
#define LASR_VISION_MSGS_MESSAGE_TORCHFACEFEATUREDETECTION_H

#include <ros/service_traits.h>


#include <lasr_vision_msgs/TorchFaceFeatureDetectionRequest.h>
#include <lasr_vision_msgs/TorchFaceFeatureDetectionResponse.h>


namespace lasr_vision_msgs
{

struct TorchFaceFeatureDetection
{

typedef TorchFaceFeatureDetectionRequest Request;
typedef TorchFaceFeatureDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TorchFaceFeatureDetection
} // namespace lasr_vision_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetection > {
  static const char* value()
  {
    return "71d0419cc4eccd880efd242219ef83a4";
  }

  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetection&) { return value(); }
};

template<>
struct DataType< ::lasr_vision_msgs::TorchFaceFeatureDetection > {
  static const char* value()
  {
    return "lasr_vision_msgs/TorchFaceFeatureDetection";
  }

  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetection&) { return value(); }
};


// service_traits::MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest> should match
// service_traits::MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetection >
template<>
struct MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetection >::value();
  }
  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest> should match
// service_traits::DataType< ::lasr_vision_msgs::TorchFaceFeatureDetection >
template<>
struct DataType< ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::lasr_vision_msgs::TorchFaceFeatureDetection >::value();
  }
  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse> should match
// service_traits::MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetection >
template<>
struct MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lasr_vision_msgs::TorchFaceFeatureDetection >::value();
  }
  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse> should match
// service_traits::DataType< ::lasr_vision_msgs::TorchFaceFeatureDetection >
template<>
struct DataType< ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::lasr_vision_msgs::TorchFaceFeatureDetection >::value();
  }
  static const char* value(const ::lasr_vision_msgs::TorchFaceFeatureDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASR_VISION_MSGS_MESSAGE_TORCHFACEFEATUREDETECTION_H
