(cl:defpackage lasr_interaction_server-srv
  (:use )
  (:export
   "SPEECHINTERACTION"
   "<SPEECHINTERACTION-REQUEST>"
   "SPEECHINTERACTION-REQUEST"
   "<SPEECHINTERACTION-RESPONSE>"
   "SPEECHINTERACTION-RESPONSE"
   "TEXTINTERACTION"
   "<TEXTINTERACTION-REQUEST>"
   "TEXTINTERACTION-REQUEST"
   "<TEXTINTERACTION-RESPONSE>"
   "TEXTINTERACTION-RESPONSE"
  ))

